# yamllint configuration
# Run: uv run yamllint .

extends: default

rules:
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]

ignore: |
  .git/
  .venv/
  library/
  node_modules/
  *.lock
