name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["chinga-chinga"]
body:
  - type: input
    id: branch_name
    attributes:
      label: Branch Name
      description: What branch will this be worked on?
      placeholder: "feature/description-of-feature"
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: What problem would this feature solve?
      placeholder: As a network engineer, I want to ...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project would this affect?
      options:
        - Backend (network_synapse)
        - Workers (synapse_workers)
        - CI/CD
        - Docker / Infrastructure
        - Documentation
        - Other
    validations:
      required: true
