name: Task
description: A development task or chore
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Backend (network_synapse)
        - Workers (synapse_workers)
        - CI/CD
        - Docker / Infrastructure
        - Documentation
        - Other
    validations:
      required: true
